// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace Elder.Framework.MessagePack.Generated.Formatters.Elder.Game.Resource.Data
{
    public sealed class MsgPTestSheetDODFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Elder.Game.Resource.Data.MsgPTestSheetDOD>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Elder.Game.Resource.Data.MsgPTestSheetDOD value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(3);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<FixedString32Bytes>(formatterResolver).Serialize(ref writer, value.key, options);
            writer.Write(value.id);
            writer.Write(value.value);
        }

        public global::Elder.Game.Resource.Data.MsgPTestSheetDOD Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __key__ = default(FixedString32Bytes);
            var __id__ = default(int);
            var __value__ = default(int);

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        __key__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<FixedString32Bytes>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        __id__ = reader.ReadInt32();
                        break;
                    case 2:
                        __value__ = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Elder.Game.Resource.Data.MsgPTestSheetDOD(__key__, __id__, __value__);
            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name
