// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1649 // File name should match first type name

namespace Elder.SkillTrial.Resources.Data.Resolvers
{
    public class GeneratedResolver : global::MessagePack.IFormatterResolver
    {
        public static readonly global::MessagePack.IFormatterResolver Instance = new GeneratedResolver();

        private GeneratedResolver()
        {
        }

        public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
        {
            return FormatterCache<T>.Formatter;
        }

        private static class FormatterCache<T>
        {
            internal static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> Formatter;

            static FormatterCache()
            {
                var f = GeneratedResolverGetFormatterHelper.GetFormatter(typeof(T));
                if (f != null)
                {
                    Formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                }
            }
        }
    }

    internal static class GeneratedResolverGetFormatterHelper
    {
        private static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

        static GeneratedResolverGetFormatterHelper()
        {
            lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(7)
            {
                { typeof(global::System.Collections.Generic.List<LanguageType>), 0 },
                { typeof(global::Elder.SkillTrial.Resources.Data.AudioSettings), 1 },
                { typeof(global::Elder.SkillTrial.Resources.Data.BootstrapData), 2 },
                { typeof(global::Elder.SkillTrial.Resources.Data.ErrorCode), 3 },
                { typeof(global::Elder.SkillTrial.Resources.Data.GraphicsSettings), 4 },
                { typeof(global::Elder.SkillTrial.Resources.Data.LocaleSettings), 5 },
                { typeof(global::Elder.SkillTrial.Resources.Data.SceneInfo), 6 },
            };
        }

        internal static object GetFormatter(global::System.Type t)
        {
            int key;
            if (!lookup.TryGetValue(t, out key))
            {
                return null;
            }

            switch (key)
            {
                case 0: return new global::MessagePack.Formatters.ListFormatter<LanguageType>();
                case 1: return new Elder.SkillTrial.Resources.Data.Formatters.Elder.SkillTrial.Resources.Data.AudioSettingsFormatter();
                case 2: return new Elder.SkillTrial.Resources.Data.Formatters.Elder.SkillTrial.Resources.Data.BootstrapDataFormatter();
                case 3: return new Elder.SkillTrial.Resources.Data.Formatters.Elder.SkillTrial.Resources.Data.ErrorCodeFormatter();
                case 4: return new Elder.SkillTrial.Resources.Data.Formatters.Elder.SkillTrial.Resources.Data.GraphicsSettingsFormatter();
                case 5: return new Elder.SkillTrial.Resources.Data.Formatters.Elder.SkillTrial.Resources.Data.LocaleSettingsFormatter();
                case 6: return new Elder.SkillTrial.Resources.Data.Formatters.Elder.SkillTrial.Resources.Data.SceneInfoFormatter();
                default: return null;
            }
        }
    }
}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1649 // File name should match first type name




// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY MPC(MessagePack-CSharp). DO NOT CHANGE IT.
// </auto-generated>

#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 168
#pragma warning disable CS1591 // document public APIs

#pragma warning disable SA1129 // Do not use default value type constructor
#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1312 // Variable names should begin with lower-case letter
#pragma warning disable SA1403 // File may only contain a single namespace
#pragma warning disable SA1649 // File name should match first type name

namespace Elder.SkillTrial.Resources.Data.Formatters.Elder.SkillTrial.Resources.Data
{
    public sealed class AudioSettingsFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Elder.SkillTrial.Resources.Data.AudioSettings>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Elder.SkillTrial.Resources.Data.AudioSettings value, global::MessagePack.MessagePackSerializerOptions options)
        {
            writer.WriteArrayHeader(7);
            writer.Write(value.Id);
            writer.Write(value.MasterVolume);
            writer.Write(value.BgmVolume);
            writer.Write(value.SfxVolume);
            writer.Write(value.VoiceVolume);
            writer.Write(value.UiVolume);
            writer.Write(value.MuteOnBackground);
        }

        public global::Elder.SkillTrial.Resources.Data.AudioSettings Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            var length = reader.ReadArrayHeader();
            var __Id__ = default(int);
            var __MasterVolume__ = default(float);
            var __BgmVolume__ = default(float);
            var __SfxVolume__ = default(float);
            var __VoiceVolume__ = default(float);
            var __UiVolume__ = default(float);
            var __MuteOnBackground__ = default(bool);

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        __Id__ = reader.ReadInt32();
                        break;
                    case 1:
                        __MasterVolume__ = reader.ReadSingle();
                        break;
                    case 2:
                        __BgmVolume__ = reader.ReadSingle();
                        break;
                    case 3:
                        __SfxVolume__ = reader.ReadSingle();
                        break;
                    case 4:
                        __VoiceVolume__ = reader.ReadSingle();
                        break;
                    case 5:
                        __UiVolume__ = reader.ReadSingle();
                        break;
                    case 6:
                        __MuteOnBackground__ = reader.ReadBoolean();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Elder.SkillTrial.Resources.Data.AudioSettings(__Id__, __MasterVolume__, __BgmVolume__, __SfxVolume__, __VoiceVolume__, __UiVolume__, __MuteOnBackground__);
            reader.Depth--;
            return ____result;
        }
    }

    public sealed class BootstrapDataFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Elder.SkillTrial.Resources.Data.BootstrapData>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Elder.SkillTrial.Resources.Data.BootstrapData value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(3);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Key, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.DataKey, options);
            writer.Write(value.Id);
        }

        public global::Elder.SkillTrial.Resources.Data.BootstrapData Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __Key__ = default(string);
            var __DataKey__ = default(string);
            var __Id__ = default(int);

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        __Key__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        __DataKey__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        __Id__ = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Elder.SkillTrial.Resources.Data.BootstrapData(__Key__, __DataKey__, __Id__);
            reader.Depth--;
            return ____result;
        }
    }

    public sealed class ErrorCodeFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Elder.SkillTrial.Resources.Data.ErrorCode>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Elder.SkillTrial.Resources.Data.ErrorCode value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(5);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Key, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.LocaleKey, options);
            writer.Write(value.Id);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<ErrorCategory>(formatterResolver).Serialize(ref writer, value.Category, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<ErrorActionType>(formatterResolver).Serialize(ref writer, value.Action, options);
        }

        public global::Elder.SkillTrial.Resources.Data.ErrorCode Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __Key__ = default(string);
            var __LocaleKey__ = default(string);
            var __Id__ = default(int);
            var __Category__ = default(ErrorCategory);
            var __Action__ = default(ErrorActionType);

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        __Key__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        __LocaleKey__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        __Id__ = reader.ReadInt32();
                        break;
                    case 3:
                        __Category__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<ErrorCategory>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        __Action__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<ErrorActionType>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Elder.SkillTrial.Resources.Data.ErrorCode(__Key__, __LocaleKey__, __Id__, __Category__, __Action__);
            reader.Depth--;
            return ____result;
        }
    }

    public sealed class GraphicsSettingsFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Elder.SkillTrial.Resources.Data.GraphicsSettings>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Elder.SkillTrial.Resources.Data.GraphicsSettings value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(5);
            writer.Write(value.Id);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<FramerateType>(formatterResolver).Serialize(ref writer, value.TargetFrameRate, options);
            writer.Write(value.VsyncCount);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<QualityLevel>(formatterResolver).Serialize(ref writer, value.QualityLevel, options);
            writer.Write(value.ScreenSleepTimeout);
        }

        public global::Elder.SkillTrial.Resources.Data.GraphicsSettings Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __Id__ = default(int);
            var __TargetFrameRate__ = default(FramerateType);
            var __VsyncCount__ = default(int);
            var __QualityLevel__ = default(QualityLevel);
            var __ScreenSleepTimeout__ = default(int);

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        __Id__ = reader.ReadInt32();
                        break;
                    case 1:
                        __TargetFrameRate__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<FramerateType>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        __VsyncCount__ = reader.ReadInt32();
                        break;
                    case 3:
                        __QualityLevel__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<QualityLevel>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 4:
                        __ScreenSleepTimeout__ = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Elder.SkillTrial.Resources.Data.GraphicsSettings(__Id__, __TargetFrameRate__, __VsyncCount__, __QualityLevel__, __ScreenSleepTimeout__);
            reader.Depth--;
            return ____result;
        }
    }

    public sealed class LocaleSettingsFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Elder.SkillTrial.Resources.Data.LocaleSettings>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Elder.SkillTrial.Resources.Data.LocaleSettings value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(2);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::System.Collections.Generic.List<LanguageType>>(formatterResolver).Serialize(ref writer, value.SupportedLanguages, options);
            writer.Write(value.Id);
        }

        public global::Elder.SkillTrial.Resources.Data.LocaleSettings Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __SupportedLanguages__ = default(global::System.Collections.Generic.List<LanguageType>);
            var __Id__ = default(int);

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        __SupportedLanguages__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<global::System.Collections.Generic.List<LanguageType>>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        __Id__ = reader.ReadInt32();
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Elder.SkillTrial.Resources.Data.LocaleSettings(__SupportedLanguages__, __Id__);
            reader.Depth--;
            return ____result;
        }
    }

    public sealed class SceneInfoFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::Elder.SkillTrial.Resources.Data.SceneInfo>
    {

        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::Elder.SkillTrial.Resources.Data.SceneInfo value, global::MessagePack.MessagePackSerializerOptions options)
        {
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            writer.WriteArrayHeader(4);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.Key, options);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Serialize(ref writer, value.SceneKey, options);
            writer.Write(value.Id);
            global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<SceneLoadType>(formatterResolver).Serialize(ref writer, value.LoadMode, options);
        }

        public global::Elder.SkillTrial.Resources.Data.SceneInfo Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            if (reader.TryReadNil())
            {
                throw new global::System.InvalidOperationException("typecode is null, struct not supported");
            }

            options.Security.DepthStep(ref reader);
            global::MessagePack.IFormatterResolver formatterResolver = options.Resolver;
            var length = reader.ReadArrayHeader();
            var __Key__ = default(string);
            var __SceneKey__ = default(string);
            var __Id__ = default(int);
            var __LoadMode__ = default(SceneLoadType);

            for (int i = 0; i < length; i++)
            {
                switch (i)
                {
                    case 0:
                        __Key__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 1:
                        __SceneKey__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<string>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    case 2:
                        __Id__ = reader.ReadInt32();
                        break;
                    case 3:
                        __LoadMode__ = global::MessagePack.FormatterResolverExtensions.GetFormatterWithVerify<SceneLoadType>(formatterResolver).Deserialize(ref reader, options);
                        break;
                    default:
                        reader.Skip();
                        break;
                }
            }

            var ____result = new global::Elder.SkillTrial.Resources.Data.SceneInfo(__Key__, __SceneKey__, __Id__, __LoadMode__);
            reader.Depth--;
            return ____result;
        }
    }

}

#pragma warning restore 168
#pragma warning restore 414
#pragma warning restore 618
#pragma warning restore 612

#pragma warning restore SA1129 // Do not use default value type constructor
#pragma warning restore SA1309 // Field names should not begin with underscore
#pragma warning restore SA1312 // Variable names should begin with lower-case letter
#pragma warning restore SA1403 // File may only contain a single namespace
#pragma warning restore SA1649 // File name should match first type name

